# Memory Builder Configuration
# Processes YAML profiles into JSONL entities for Claude's Memory System

build:
  process:
    additionalProfiles: false
    commonProfilesFirst: true
  stopOnCriticalError: true
  outputPath: ./../../memory.json
  profiles:
    - creative.yaml
    - developer.yaml
    - engineer.yaml
    - humanist.yaml
    - researcher.yaml
  profilesPath:
    common: ./profiles/common
    domain: ./profiles
  relations:
    - extends
    - inherits
    - overrides

logging:
  showFileDetails: true
  showProgress: true

path:
  conversations: /Volumes/backup/claude/conversations
  diary: /Volumes/backup/claude/diary
  tool: ~/github/claude/.claude/tools/memory
