# Memory Builder Configuration
# Processes YAML profiles into JSONL entities for Claude's memory system

build:
  autoDetectProfiles: false
  processAdditionalFiles: false
  processCommonFirst: true
  stopOnCriticalError: true
  profiles:
    - creative.yaml
    - engineer.yaml
    - humanist.yaml
    - researcher.yaml
  profilesPath:
    common: common
    standard: profiles

logging:
  showFileDetails: true
  showProgress: true

output:
  path: ./config/server.json
  format: jsonl

path:
  conversations: /Volumes/backup/claude/conversations
  diary: /Volumes/backup/claude/diary
  tool: ~/github/claude/tools/memory

performance:
  showBuildTime: true
  showStatistics: true

workflow:
  user:
    email: 41898282+github-actions[bot]@users.noreply.github.com
    name: github-actions[bot]
