# Memory Builder Configuration
# Processes YAML profiles into JSONL entities for Claude's memory system

build:
  processAdditionalFiles: false
  processCommonFirst: true
  stopOnCriticalError: true
  outputPath: ./config/server.json
  profiles:
    - creative.yaml
    - developer.yaml
    - engineer.yaml
    - humanist.yaml
    - researcher.yaml
  profilesPath:
    common: ./profiles/common
    standard: ./profiles
  relations:
    - extends
    - inherits
    - overrides

logging:
  showFileDetails: true
  showProgress: true

path:
  conversations: /Volumes/backup/claude/conversations
  diary: /Volumes/backup/claude/diary
  tool: ~/github/claude/tools/memory
