# Memory Builder Configuration
# Processes YAML profiles into JSONL entities for Claude's memory system

build:
  commonDirectory: common
  autoDetectProfiles: false
  profiles:
    - creative.yaml
    - engineer.yaml
    - humanist.yaml
    - researcher.yaml
  profilesDirectory: profiles
  processCommonFirst: true
  processAdditionalFiles: false
  stopOnCriticalError: true

path:
  conversations: /Volumes/backup/claude/conversations
  diary: /Volumes/backup/claude/diary
  tool: ~/github/claude/tools/memory

output:
  path: ./config/server.json
  format: jsonl

performance:
  showStatistics: true
  showBuildTime: true

logging:
  showProgress: true
  showFileDetails: true
