name: Memory

on:
  pull_request:
    paths:
      - tools/memory/**

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build memory configuration
        uses: actions/github-script@v7
        with:
          script: |
            const { Workflow } = require('./tools/memory/lib');
            const workflow = new Workflow({ core, exec });
            await workflow.execute();
