name: Memory

on:
  pull_request:
    paths:
      - .claude/memory/**
      - .github/actions/**
      - .github/workflows/memory.yml

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

permissions:
  checks: write
  contents: write
  issues: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install node dependencies
        run: npm install handlebars js-yaml

      - name: Configure repository
        id: workflow
        uses: actions/github-script@v8
        with:
          script: |
            const { Workflow } = require('./.github/actions/handlers');
            const workflow = new Workflow({ github, context, core, exec });
            await workflow.configureRepository();

      - name: Build memory graph
        uses: actions/github-script@v8
        with:
          script: |
            const { Workflow } = require('./.github/actions/handlers');
            const workflow = new Workflow({ github, context, core, exec });
            await workflow.build();

      - name: Report workflow issue
        uses: actions/github-script@v8
        if: always()
        with:
          script: |
            const { Workflow } = require('./.github/actions/handlers');
            const workflow = new Workflow({ github, context, core, exec });
            await workflow.reportIssue();
